#!/bin/bash

ls > initialState.txt 
mkdir directoryListings 
g++ helloWorld.cpp -o helloWorldExecutable
mv initialState.txt directoryListings
mv songs.txt list.txt
ls -l > directoryListings/updated.txt
ls -l exampleDirectory > directoryListings/example.txt
ls -l intermediateLab > directoryListings/intermediate1.txt
cd intermediateLab && make && cd ..
